document.writeln('<script language=\"JScript\">');
document.writeln('<!-- // DDMenu');
document.writeln('');
document.writeln('  var eOpenMenu = null;');
document.writeln('  function OpenMenu(eSrc,eMenu){');
document.writeln('    eMenu.style.left = eSrc.parentElement.offsetLeft + divMenuBar.offsetLeft;');
document.writeln('    eMenu.style.top = divMenuBar.offsetHeight + divMenuBar.offsetTop;');
document.writeln('    eMenu.style.visibility = \"visible\";');
document.writeln('    eOpenMenu = eMenu;');
document.writeln('  }');
document.writeln('');
document.writeln('  function CloseMenu(eMenu){');
document.writeln('    eMenu.style.visibility = \"hidden\";');
document.writeln('    eOpenMenu = null;');
document.writeln('  }');
document.writeln('');
document.writeln('  function MenuBar_over(){');
document.writeln('    var eSrc = window.event.srcElement;');
document.writeln('    if (\"A\" == eSrc.tagName.toUpperCase()){');
document.writeln('      var eMenu = document.all[eSrc.parentElement.id.replace(\"tdMenuBarItem\",\"divMenu\")];');
document.writeln('      if (eOpenMenu && eOpenMenu != eMenu){');
document.writeln('        CloseMenu(eOpenMenu);}');
document.writeln('      if (eMenu){');
document.writeln('		  OpenMenu(eSrc,eMenu);}');
document.writeln('    }');
document.writeln('  }');
document.writeln('');
document.writeln('  function MenuBar_out(){');
document.writeln('    var eTo = window.event.toElement;');
document.writeln('    if (eOpenMenu && eTo && !eOpenMenu.contains(eTo) && \"tblMenuBar\" != eTo.id){');
document.writeln('      CloseMenu(eOpenMenu)}');
document.writeln('	}');
document.writeln('');
document.writeln('  function Menu_out(){');
document.writeln('    var eSrc = window.event.toElement;');
document.writeln('    if (eOpenMenu && !eOpenMenu.contains(eSrc) && !divMenuBar.contains(eSrc)){');
document.writeln('      CloseMenu(eOpenMenu)}');
document.writeln('	}');
document.writeln('');
document.writeln('//-->');
document.writeln('</script>');
document.writeln('<style type=\"text/css\">');
document.writeln('	BODY { font-family:\"Verdana, Arial, Helvetica, sans-serif\"; font-size:70%;}');
document.writeln('');
document.writeln('	DIV#divMenuBar { background-color:#00cc00; }');
document.writeln('	TABLE#tblMenuBar TD { font-size:60%; color:#FFFFFF; padding:0px 5px 0px 5px; cursor:default; }');
document.writeln('	TABLE#tblMenuBar TD.clsMenuBarItem { font-weight:bold; cursor:default; }');
document.writeln('');
document.writeln('	/* These two style rules added for links in MenuBar */');
document.writeln('	TABLE#tblMenuBar TD.clsMenuBarItem A { text-decoration:none; color:#000000; font-weight:bold; }');
document.writeln('	TABLE#tblMenuBar TD.clsMenuBarItem A:hover { color:#FFFFFF; }');
document.writeln('	DIV.clsMenu { ');
document.writeln('		font-size:90%; background-color:#00cc00;');
document.writeln('		position:absolute; visibility:hidden; width:180px; ');
document.writeln('		padding:5px 5px 5px 8px; border-top:1 white solid; ');
document.writeln('	}');
document.writeln('	DIV.clsMenu A { text-decoration:none; color:#000000; font-weight:bold; }');
document.writeln('	DIV.clsMenu A:hover { color:#FFFFFF; }');
document.writeln('</style>');
document.writeln(' <ddMenu> ');
document.writeln('<DIV ID=\"ddMenuLayer\" STYLE=\"position:absolute; left:0px; top:0px; width:100%; height:35px; z-index:1\"> ');
document.writeln('  <DIV ID=\"divMenuBar\" ONMOUSEOVER=\"if (document.all) MenuBar_over();\" ONMOUSEOUT=\"if (document.all) MenuBar_out();\" ONSELECTSTART=\"return false;\"> ');
document.writeln('    <TABLE ID=\"tblMenuBar\" BORDER=\"0\" WIDTH=\"100%\">');
document.writeln('      <TR> ');
document.writeln('        <TD CLASS=\"clsMenuBarItem\" ID=\"tdMenuBarItemPrincipal\"> <A TARGET=\"\" HREF=\"Principal.asp\">Principal</A> ');
document.writeln('        </TD>');
document.writeln('        <TD>|</TD>');
document.writeln('        <TD CLASS=\"clsMenuBarItem\" ID=\"tdMenuBarItemAbonados\"> <A TARGET=\"\" HREF=\"#\">Abonados</A> ');
document.writeln('        </TD>');
document.writeln('        <TD>|</TD>');
document.writeln('        <TD CLASS=\"clsMenuBarItem\" ID=\"tdMenuBarItemListados\"> <A TARGET=\"\" HREF=\"#\">Listados</A> ');
document.writeln('        </TD>');
document.writeln('        <TD>|</TD>');
document.writeln('        <TD CLASS=\"clsMenuBarItem\" ID=\"tdMenuBarItemProfesionales\"> <A TARGET=\"\" HREF=\"#\">Profesionales</A> ');
document.writeln('        </TD>');
document.writeln('        <TD>|</TD>');
document.writeln('        <TD CLASS=\"clsMenuBarItem\" ID=\"tdMenuBarItemCitas\"> <A TARGET=\"\" HREF=\"#\">Citas</A> ');
document.writeln('        </TD>');
document.writeln('        <TD>|</TD>');
document.writeln('        <TD CLASS=\"clsMenuBarItem\" ID=\"tdMenuBarItemAgentes\"> <A TARGET=\"\" HREF=\"#\">Agentes</A> ');
document.writeln('        </TD>');
document.writeln('        <TD>|</TD>');
document.writeln('        <TD>|</TD>');
document.writeln('        <TD CLASS=\"clsMenuBarItem\" ID=\"tdMenuBarItemOpciones\"> <A TARGET=\"\" HREF=\"#\">Opciones</A> ');
document.writeln('        </TD>');
document.writeln('        <TD>|</TD>');
document.writeln('        <TD CLASS=\"clsMenuBarItem\" ID=\"tdMenuBarItemPrincipal\"> <A TARGET=\"\" HREF=\"Principal.asp?MM_Logoutnow=1\">Desconectar</A> ');
document.writeln('        </TD>');
//document.writeln('        <TD>|</TD>');
//document.writeln('        <TD CLASS=\"clsMenuBarItem\" ID=\"tdMenuBarItemPrincipal\"> <A TARGET=\"blank\" HREF=\"Seguros/principal.asp\">Seguros</A> ');
//document.writeln('        </TD>');
//document.writeln('        <TD CLASS=\"clsMenuBarItem\" ID=\"tdMenuBarItemPrincipal\"> <form name=\"form1\" method=\"post\" action=\"\"><input type=\"text\" name=\"texto\" style=\"FONT-FAMILY:Verdana,Arial,Helvetica; FONT-SIZE:6.5pt; width:210\" size=15></form>');
//document.writeln('        </TD>');
//document.writeln('        <TD WIDTH=\"100%\" align=\"right\"><span id=\"jvsfclock\"></span><a href=\"#\"><img src=\"Imagenes/cerrar.gif\" alt=\"Cerrar Barra\" onClick=\"CloseMenu(ddMenuLayer);\" border=0></a></TD>');
document.writeln('        <TD WIDTH=\"100%\" align=\"right\"><%=Session("MM_Username")%><a href=\"#\"><img src=\"Imagenes/cerrar.gif\" alt=\"Cerrar Barra\" onClick=\"CloseMenu(ddMenuLayer);\" border=0></a></TD>');
document.writeln('      </TR>');
document.writeln('    </TABLE>');
document.writeln('  </DIV>');
document.writeln('  <DIV CLASS=\"clsMenu\" ONMOUSEOUT=\"Menu_out();\" ID=\"divMenuAbonados\"> ');
document.writeln('    <DIV CLASS=\"clsMenuSpacer\"></DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"ClienteBuscar.asp\">Buscar</A> </DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"clienteNuevo.asp\">Insertar</A> </DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"AbonosQueCaducan.asp\">Lista de abonos que caducan</A> </DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"AbonosCaducados.asp\">Abonos caducados</A> </DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"ClientesMailing.asp\">Listado para Mailing</A> </DIV>');
document.writeln('  </DIV>');
document.writeln('  <DIV CLASS=\"clsMenu\" ONMOUSEOUT=\"Menu_out();\" ID=\"divMenuListados\"> ');
document.writeln('    <DIV CLASS=\"clsMenuSpacer\"></DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"FacturasListado.asp?Sector=1\">Facturas</A> </DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"SiniestrosListar.asp?Sector=1\">Siniestros por profesional</A> </DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"AbonadosListar.asp\">Abonados</A> </DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"SiniestrosListar2.asp\">Siniestros</A></DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"SiniestroOtrosListar.asp\">Siniestros no trafico</A></DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"ListadoCiaContraria.asp\">Siniestros por cia contraria</A></DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"PagosSinHacer.asp\">Pagos sin hacer</A></DIV> ');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"ComisionesSinCobrar.asp\">Comisiones sin cobrar</A></DIV> ');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"FacturasAdelantadas.asp\">Facturas adelantadas</A></DIV> ');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"ListadoCobrados.asp\">Listado de cobrados</A></DIV> ');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"ListadoProblemasAJ.asp\">Listado de problemas con la AJ</A></DIV> ');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"Informe.asp\">Informe</A></DIV> ');
//document.writeln('    <DIV> <A TARGET=\"\" HREF=\"AbonadosJJulio.asp\">Abonados para J.Julio</A> </DIV>');
document.writeln('  </DIV>');
document.writeln('  <DIV CLASS=\"clsMenu\" ONMOUSEOUT=\"Menu_out();\" ID=\"divMenuProfesionales\"> ');
document.writeln('    <DIV CLASS=\"clsMenuSpacer\"></DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"ProfesionalInsertar.asp\">Insertar Profesional</A> </DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"ProfesionalListar.asp\">Consultar/Modificar Profesional</A> </DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"ProfesionalMailing.asp\">Listado para mailing</A> </DIV>');
document.writeln('  </DIV>');
document.writeln('  <DIV CLASS=\"clsMenu\" ONMOUSEOUT=\"Menu_out();\" ID=\"divMenuCitas\"> ');
document.writeln('    <DIV CLASS=\"clsMenuSpacer\"></DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"AgendaInsertar.asp\">Insertar Cita</A> </DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"AgendaListar.asp\">Mostrar Citas</A> </DIV>');
document.writeln('  </DIV>');
document.writeln('  <DIV CLASS=\"clsMenu\" ONMOUSEOUT=\"Menu_out();\" ID=\"divMenuAgentes\"> ');
document.writeln('    <DIV CLASS=\"clsMenuSpacer\"></DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"AgenteInsertar.asp\">Insertar Agente</A> </DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"AgenteListar.asp\">Consultar/Modificar Agente</A> </DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"AgentesEfectivos.asp\">Listado de agentes efectivos</A> </DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"agentesvisitaslistado.asp\">Listado de visitas</A> </DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"AgenteMailing.asp\">Listado para mailing</A> </DIV>');
document.writeln('  </DIV>');
document.writeln('  <DIV CLASS=\"clsMenu\" ONMOUSEOUT=\"Menu_out();\" ID=\"divMenuopciones\"> ');
document.writeln('    <DIV CLASS=\"clsMenuSpacer\"></DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"ClienteBuscar.asp\">Buscar</A> </DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"clienteNuevo.asp\">Insertar</A> </DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"AbonosQueCaducan.asp\">Lista de abonos que caducan</A> </DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"AbonosCaducados.asp\">Abonos caducados</A> </DIV>');
document.writeln('    <DIV> <A TARGET=\"\" HREF=\"ClientesMailing.asp\">Listado para Mailing</A> </DIV>');
document.writeln('  </DIV>');
document.writeln('</DIV>');

document.writeln('</ddmenu> ');
/*function show2(){
if (!document.all&&!document.getElementById)
return
var thelement=document.getElementById? document.getElementById("jvsfclock"): document.all.jvsfclock
var Digital=new Date()
var hours=Digital.getHours()
var minutes=Digital.getMinutes()
var seconds=Digital.getSeconds()
var ctime=Digital.getDate()+"/"+Digital.getMonth()+"/"+Digital.getYear()+" "+hours+":"+minutes+":"+seconds
thelement.innerHTML=ctime
setTimeout("show2()",1000)
}
window.onload=show2*/