<script language="JavaScript" type="text/javascript" src="./menu/avata_scr.js">
</script>

<table  id="m1mainSXMenu2" cellspacing="1" cellpadding="4" class="x1" border="0" width="100%">
<tr align="left">
<td onmouseover="chgBg(m1,'m1tlm0',3);exM(m1,'none','',event)"
onmouseout="chgBg(m1,'m1tlm0',0,1)"  id="m1tlm0"  class="m1mit" 
 bgcolor="#FF8000">

<a id="m1tlm0a" class="m1CL0" href="Principal.asp" >
<div class='topFold'>Principal</div></a></td>
<td onmouseover="chgBg(m1,'m1tlm1',3);exM(m1,'m1mn1','m1tlm1',event)"
onmouseout="chgBg(m1,'m1tlm1',0);coM(m1,'m1mn1')"  id="m1tlm1"  class="m1mit" 
 bgcolor="#FF8000">
<a id="m1tlm1a" class="m1CL0" href="javascript:void(0);" onMouseOver="exMNS(m1,'m1mn1',event)"
onmouseout="coMNS(m1,'m1mn1')" >
<div id='m1mn1top' class='topFold'>Abonados<img width="8" height="8" src="./menu/avata_m1iad.gif" align="texttop" border="0" /></div></a></td>
<td onmouseover="chgBg(m1,'m1tlm2',3);exM(m1,'m1mn2','m1tlm2',event)"
onmouseout="chgBg(m1,'m1tlm2',0);coM(m1,'m1mn2')"  id="m1tlm2"  class="m1mit" 
 bgcolor="#FF8000">
<a id="m1tlm2a" class="m1CL0" href="javascript:void(0);" onMouseOver="exMNS(m1,'m1mn2',event)"
onmouseout="coMNS(m1,'m1mn2')" >
<div id='m1mn2top' class='topFold'>Listados<img width="8" height="8" src="./menu/avata_m1iad.gif" align="texttop" border="0" /></div></a></td>
<td onmouseover="chgBg(m1,'m1tlm3',3);exM(m1,'m1mn3','m1tlm3',event)"
onmouseout="chgBg(m1,'m1tlm3',0);coM(m1,'m1mn3')"  id="m1tlm3"  class="m1mit" 
 bgcolor="#FF8000">
<a id="m1tlm3a" class="m1CL0" href="javascript:void(0);" onMouseOver="exMNS(m1,'m1mn3',event)"
onmouseout="coMNS(m1,'m1mn3')" >
<div id='m1mn3top' class='topFold'>Profesionales<img width="8" height="8" src="./menu/avata_m1iad.gif" align="texttop" border="0" /></div></a></td>
<td onmouseover="chgBg(m1,'m1tlm4',3);exM(m1,'m1mn4','m1tlm4',event)"
onmouseout="chgBg(m1,'m1tlm4',0);coM(m1,'m1mn4')"  id="m1tlm4"  class="m1mit" 
 bgcolor="#FF8000">
<a id="m1tlm4a" class="m1CL0" href="javascript:void(0);" onMouseOver="exMNS(m1,'m1mn4',event)"
onmouseout="coMNS(m1,'m1mn4')" >
<div id='m1mn4top' class='topFold'>Citas<img width="8" height="8" src="./menu/avata_m1iad.gif" align="texttop" border="0" /></div></a></td>
<td onmouseover="chgBg(m1,'m1tlm5',3);exM(m1,'m1mn5','m1tlm5',event)"
onmouseout="chgBg(m1,'m1tlm5',0);coM(m1,'m1mn5')"  id="m1tlm5"  class="m1mit" 
 bgcolor="#FF8000">
<a id="m1tlm5a" class="m1CL0" href="javascript:void(0);" onMouseOver="exMNS(m1,'m1mn5',event)"
onmouseout="coMNS(m1,'m1mn5')" >
<div id='m1mn5top' class='topFold'>Agentes<img width="8" height="8" src="./menu/avata_m1iad.gif" align="texttop" border="0" /></div></a></td>
<td onmouseover="chgBg(m1,'m1tlm6',3);exM(m1,'none','',event)"
onmouseout="chgBg(m1,'m1tlm6',0,1)"  id="m1tlm6"  class="m1mit" 
 bgcolor="#FF8000">
<a id="m1tlm6a" class="m1CL0" href="Principal.asp?MM_Logoutnow=1" >
<div class='topFold'>Desconectar</div></a></td></tr></table>