<div id='cssmenu'>
<ul>
   <li><a href='Principal.asp'><span>Principal</span></a></li>
   <li class='has-sub'><a href='#'><span>Abonados</span></a>
      <ul>
         <li><a href='#'><span>Buscar</span></a></li>
         <li><a href='clienteNuevo.asp'><span>Insertar</span></a></li>
         <li><a href='AbonosQueCaducan.asp'><span>Lista de Abonos que caducan</span></a></li>
         <li><a href='AbonosCaducados.asp'><span>Abonos caducados</span></a></li>
         <li class='last'><a href='ClientesMailing.asp'><span>Listado para Mailing</span></a></li>
      </ul>
   </li>
   <li class='has-sub'><a href='#'><span>Listados</span></a>
      <ul>
         <li><a href='FacturasListado.asp?Sector=1'><span>Facturas</span></a></li>
         <li><a href='SiniestrosListar.asp?Sector=1'><span>Siniestros por profesional  </span></a></li>
         <li><a href='AbonadosListar.asp'><span>Abonados</span></a></li>
         <li><a href='SiniestrosListar2.asp'><span>Siniestros</span></a></li>
         <li><a href='SiniestroOtrosListar.asp'><span>Siniestros no trafico</span></a></li>
         <li><a href='ListadoCiaContraria.asp'><span>Siniestros por CIA contraria</span></a></li>
         <li><a href='PagosSinHacer.asp'><span>Pagos sin hacer</span></a></li>
         <li><a href='ComisionesSinCobrar.asp'><span>Comisiones sin cobrar</span></a></li>
         <li><a href='FacturasAdelantadas.asp'><span>Facturas adelantadas</span></a></li>
         <li><a href='ListadoCobrados.asp'><span>Listado de cobrados</span></a></li>
         <li><a href='ListadoProblemasAJ.asp'><span>Listado problemas AJ</span></a></li>
         <li class='last'><a href='Informe.asp'><span>Informe</span></a></li>
      </ul>
   </li>
   <li class='has-sub'><a href='#'><span>Profesionales</span></a>
      <ul>
         <li><a href='ProfesionalInsertar.asp'><span>Insertar profesional</span></a></li>
         <li><a href='ProfesionalListar.asp'><span>Consultar/Modificar profesional</span></a></li>
         <li class='last'><a href='ProfesionalMailing.asp'><span>Listado para Mailing</span></a></li>
      </ul>
   </li>
   <li class='has-sub'><a href='#'><span>Citas</span></a>
      <ul>
         <li><a href='AgendaInsertar.asp'><span>Insertar Cita</span></a></li>
         <li class='last'><a href='AgendaListar.asp'><span>Mostrar Citas</span></a></li>
      </ul>
   </li>
   <li class='has-sub'><a href='#'><span>Agentes</span></a>
      <ul>
         <li><a href='AgenteInsertar.asp'><span>Insertar Agente</span></a></li>
         <li><a href='AgenteListar.asp'><span>Consultar/Modificar agente</span></a></li>
         <li><a href='AgentesEfectivos.asp'><span>Listado de agentes efectivos</span></a></li>
         <li><a href='agentesvisitaslistado.asp'><span>Listado de visitas</span></a></li>
         <li class='last'><a href='AgenteMailing.asp'><span>Listado para Mailing</span></a></li>
      </ul>
   </li>
   <li class='last'><a href='Principal.asp?MM_Logoutnow=1'><span>Desconectar</span></a></li>
</ul>
</div>