//script generated by SiteXpert (www.xtreeme.com)
//Copyright(C) 1998-2003 Xtreeme GmbH
function f33(p){
if(p&&p.indexOf(':/')==-1&&p.indexOf(':\\')==-1&&p.indexOf('/')!=0) return unescape(absPath)+p
else return p}
function addLoadHandler(lh){
if(lh){
if(!document.loadHandlers){
document.loadHandlers=new Array()
document.loadHandlers[0]=lh
document.lastLoadHandler=0}
else{
document.lastLoadHandler++
document.loadHandlers[document.lastLoadHandler]=lh}}}
addLoadHandler('f29')
addLoadHandler(window.onload)
window.onload=f31
function f32(){return true;}
window.onerror=f32
var q;var nmn;for(nmn=1;nmn<=lastm;nmn++){q=eval('window.m'+nmn);if(q)break;}
iconTag="<IMG SRC=\'"
iconTag+=f33(q.v21)+"/"+q.fnm+"ia.gif\' BORDER=0 WIDTH="+q.iconSize+" HEIGHT="+q.iconSize+" HSPACE="+(5+q.bord)+" ALIGN=RIGHT>"
var resizeRef=(q.v19&&!q.v20)?parent:window
var startWidth=resizeRef.innerWidth
var startHeight=resizeRef.innerHeight
resizeRef.onresize=function(){
if(resizeRef.innerWidth==startWidth&&resizeRef.innerHeight==startHeight)return
resizeRef.location.reload()}
function f03(q,popup,v27,v26,v30,v09,bLast,v31,target,icon){
var itemWnd
eval("itemWnd=new Layer(q.v23,popup)")
var fnt=v09[6]
var cl=fnt.indexOf(',')
if(cl!=-1)fnt=fnt.substring(0,cl)
var itemHoverText="<font style='font-size:"+v09[0]+";width:"+(q.v23-q.vertSpace*2-q.bord*2)+"' color="+v09[5]+" face='"+fnt+"'>"+v26+"</font>"
var targetFr=""
if(v27){
var startPos=v26.indexOf('<!--')
if(q.v19&&q.v20)targetFr="target='"+q.cntFrame+"'"
if(startPos!=-1){
var endPos=v26.indexOf('-->',startPos)
targetFr="target='"+v26.substring(startPos+4,endPos)+"'"}}
if(v27)itemHoverText="<a href=\""+v27+"\" "+targetFr+" style='width:"+(q.v23-q.vertSpace*2-q.bord*2)+";text-decoration:none'>"+itemHoverText+"</a>"
if(v09[1])itemHoverText=itemHoverText.bold()
if(v09[2]&&itemHoverText.italic)itemHoverText=itemHoverText.italic()
if(v30)itemHoverText=iconTag+itemHoverText
v26="<font style='font-size:"+v09[0]+";width:"+(q.v23-q.vertSpace*2-q.bord*2)+"' color="+v09[3]+" face='"+fnt+"'>"+v26+"</font>"
if(v27)v26="<a href=\""+v27+"\" "+targetFr+" style='width:"+(q.v23-q.vertSpace*2-q.bord*2)+";text-decoration:none'>"+v26+"</a>"
if(v09[1])v26=v26.bold()
if(v09[2]&&v26.italic)v26=v26.italic()
if(v30)v26=iconTag+v26
itemWnd.captureEvents(Event.CLICK)
itemWnd.onclick=f20
f30(itemWnd,"mouseout",f23,false)
f30(itemWnd,"mouseover",f22,false)
itemWnd.document.write(v26)
itemWnd.document.close()
itemWnd.document.tags.A.textDecoration="none"
itemWnd.document.tags.FONT.width=q.v23-q.vertSpace*2-q.bord*2
itemWnd.document.tags.FONT.fontSize=v09[0]
itemWnd.pageX=q.vertSpace+q.bord
if(v30)itemWnd.v30=v30
itemWnd.owner=popup
itemWnd.url=f33(v27)
itemWnd.target=target
itemWnd.icon=icon
itemWnd.pageY=v31+q.vertSpace
itemWnd.dispText=v26
itemWnd.bHighlighted=0
itemWnd.dispHoverText=itemHoverText
itemWnd.bgColor=v09[4]?v09[4]:'white'
itemWnd.clip.top=-q.vertSpace
itemWnd.clip.left=-q.vertSpace
var newHeight=itemWnd.document.height+2*q.vertSpace
itemWnd.resizeTo(q.v23-2*q.bord,newHeight)
itemWnd.visibility="inherit"
return newHeight}
function f05(q,v12,level){
var popupName=v12+"popup"
var popup=eval("q.v18.document."+popupName)
if(popup)return popup
if(q.v17&&q.v17.wid==popupName)q.v17=null
var v09
var nm=q
if(level>q.maxlev){v09=eval("nm.lev"+q.maxlev);}else{v09=eval("nm.lev"+level);}
eval("q.v18.document."+popupName+"=new Layer(q.v23,q.v18)")
popup=eval("q.v18.document."+popupName)
popup.level=level
popup.wid=popupName
popup.v05=v09[5]
popup.v06=v09[3]
popup.v07=v09[7]?v09[7]:'white'
popup.v08=v09[4]?v09[4]:'white'
popup.zIndex=maxZ
popup.bgColor=q.bord?q.borderCol:(v09[4]?v09[4]:'white')
popup.q=q
f30(popup,"mouseout",f15,false)
f30(popup,"mouseover",f14,false)
var v31=q.bord
var array=eval(v12)
var v13
var popupText=""
for(v13=0;v13<array.length/5;v13++){
var v30=(array[v13*5+2])?(v12+"_"+parseInt(v13+1)):null
v31+=f03(q,popup,array[v13*5+1],array[v13*5],v30,v09,(v13==array.length/5-1),v31,array[v13*5+3],array[v13*5+4])
v31+=q.sep}
v31+=q.bord
popup.resizeTo(q.v23,v31)
popup.v31=v31
return popup}
function f35(q,vis){
var i=1
while(true){
var eln='HideItem'
if(i>1)eln+=i
var hideWnd=eval("q.v18.document."+eln)
if(!hideWnd)break
hideWnd.visibility=vis ? 'show' : 'hide'
i++}}
function f06(q,popupId){
if(popupId.indexOf('_')==-1)
f35(q,1)
var popup=eval("q.v18.document."+popupId)
if(popup){
if(popup.v14)f06(q,popup.v14.wid)
popup.visibility="hide"}
if(q.v17&&q.v17.wid==popupId)q.v17=null}
function f07(rect,refx,refy){
var retval=new rct(rect.left-refx,rect.top-refy,rect.right-refx,rect.bottom-refy)
return retval}
function f34(popup,actEl){
var items=popup.layers
var i=0
for(;i<items.length;i++)if(actEl!=items[i]&&(!items[i].id||items[i].id.indexOf("scroll")==-1)){
items[i].color=popup.v06
items[i].bgColor=popup.v08
if(mswnd&&items[i].bHighlighted){
items[i].document.write(items[i].dispText)
items[i].document.close()
items[i].bHighlighted=0}}}
function f08(q,popup,x,y,bDontMove){
if(popup.wid.indexOf('_')==-1)
f35(q,0)
popup.left=x
popup.top=y
popup.visibility="show"
var v16=f17(q.v18)
if(x+q.v23>v16.right)popup.left=Math.max(0,v16.right-q.v23-5-popup.level*20)
if(y+popup.v31>v16.bottom)popup.top=Math.max(0,v16.bottom-popup.v31-5)
f34(popup,null)}
function f13(q,popup){
var wnd=q.v17
while(wnd){
if(wnd.wid==popup.wid)
return true
wnd=wnd.v14}
return false}
function f14(){
var q=this.q
if(q.v17&&f13(q,this))clearTimeout(q.v17Timeout)}
function f15(){
var q=this.q
f15Impl(q,this)}
function f15Impl(q,popup){
if(q.mout&&q.v17&&f13(q,popup)){
if(q.v17Timeout)clearTimeout(q.v17Timeout)
q.v17Timeout=setTimeout("f06("+q.name+",'"+q.v17.wid+"');",q.closeDelay)}}
function rct(left,top,right,bottom){
this.left=left
this.top=top
this.right=right
this.bottom=bottom}
function f17(doc){
var left=doc.pageXOffset
var top=doc.pageYOffset
var right=left+doc.innerWidth
var bottom=top+doc.innerHeight
var retval=new rct(left,top,right,bottom)
return retval}
function f19(wnd){
var left=wnd.pageX
var top=wnd.pageY
var right=left+wnd.document.width
var bottom=top+wnd.document.height
var retval=new rct(left,top,right,bottom)
return retval}
function findFr(wn,fr){
if(wn.frames){
for(var i=0;i<wn.frames.length;i++){
if(wn.frames[i].name==fr)return wn.frames[i]
var ret=findFr(wn.frames[i],fr)
if(ret)return ret}}
return null}
function f20(){
var item=this
var q=this.owner.q
if(item.url){
var trgFrame=q.cntFrame
if(item.target)
trgFrame=item.target
if(trgFrame=="_self")
trgFrame=null
if(trgFrame){
if(trgFrame=="_blank")window.open(item.url)
else if(trgFrame=="_top")window.top.location.href=item.url
else if(trgFrame=="_parent")parent.location.href=item.url
else{
var fr=findFr(window.top,trgFrame)
if(fr)fr.location.href=item.url
else window.location.href=item.url}}
else{
var find=item.url.indexOf("javascript:")
if(find!=-1)
eval(item.url.substring(find))
else{
var mt=item.url.indexOf("mailto:")
if(mt!=-1)window.location=item.url.substring(mt)
else q.targetFrame.location=item.url}}
if(q.v17)f06(q,q.v17.id)}
return false}
function f22(){
var item=this
var q=this.owner.q
if(item.owner.v14){
f06(q,item.owner.v14.wid)}
if(item.url&&item.url.indexOf("javascript:")==-1)
window.status=item.url
else
window.status=""
f34(item.owner,item)
item.bgColor=item.owner.v07
if(mswnd){
item.document.write(item.dispHoverText)
item.document.close()
item.bHighlighted=1}
if(item.v30){
var rect=f19(item)
var x=item.pageX+q.v23-q.levelOffset
var y=rect.top
var popup=f05(q,item.v30,item.owner.level+1)
item.owner.v14=popup
f08(q,popup,x,y,false)}}
function f23(){
var item=this
var q=this.owner.q
window.status=""}
function exM(q,popupId,refWnd,e,ml,mt,mr,mb){
if(!docLoaded)return
clearTimeout(q.v17Timeout)
if(q.v17&&q.v17.wid!=popupId+"popup")
f06(q,q.v17.wid)
if(popupId=='none')return
var rect
if(refWnd=='coords'){rect=f19(document.layers[q.name+'tln']);rect.left=rect.left+ml;rect.top=rect.top+mt;rect.right=rect.left+mr;rect.bottom=rect.top+mb;}
else if(document.layers[popupId+"top"]){rect=f19(document.layers[popupId+"top"]);}
else if(e){rect=new rct(e.pageX,e.pageY,e.pageX+30,e.pageY+10);}
var x
var y
if(q.menuHorizontal){
x=rect.left
y=rect.bottom+q.popupOffset}
else{
x=rect.right+q.popupOffset
y=rect.top}
if(q.v19&&!q.v20){
var brRect=f17(q.v18)
var wRect=f17(window)
switch(q.menuPos){
case 0:
x=brRect.left+q.popupOffset
y+=brRect.top-wRect.top
break
case 1:
x=brRect.right-q.popupOffset
y+=brRect.top-wRect.top
break
case 2:
x+=brRect.left-wRect.left
y=brRect.top+q.popupOffset
break
case 3:
x+=brRect.left-wRect.left
y=brRect.bottom-q.popupOffset
break}}
var popup=f05(q,popupId,0)
f08(q,popup,x,y,true)
q.v17=popup}
function coM(q,popupId){
if(!docLoaded)return
var popup=eval("q.v18.document."+popupId+"popup")
if(popup)f15Impl(q,popup)}
function exMNS(q,popupId,e){
exM(q,popupId,e)}
function coMNS(q,popupId){
coM(q,popupId)}
function f28(){
var nmn
for(nmn=1;nmn<=lastm;nmn++){
var q=eval("window.m"+nmn)
if(q&&q.v17)f06(q,q.v17.wid)}}
function f29(){
if(docLoaded)return
var nmn
for(nmn=1;nmn<=lastm;nmn++){
var q=eval("window.m"+nmn)
if(q){
q.v18=(q.v19&&!q.v20)?findFr(window.top,q.v24):window
q.targetFrame=(q.v19)?findFr(window.top,q.cntFrame):window
if(!q.mout)f30(q.v18.document,"mousedown",f28,false)}}
docLoaded=true}
function f30(obj,event,fun,bubble){
eval("obj.on"+event+"="+fun)}
function chgBg(item,color){}
function f31(){
var i
var l=document.lastLoadHandler
document.lastLoadHandler=-1
for(i=0;i<=l;i++){
var h=document.loadHandlers[i]
if(typeof(h)!='function'){
var bPar=(h.indexOf('(')==-1)
eval(h+(bPar ? '();' : ';'))}
else{
h()}}}
