//script generated by SiteXpert (www.xtreeme.com)
//Copyright(C) 1998-2003 Xtreeme GmbH
function findElement(e,i){
return e?e.document.getElementById(i):document.getElementById(i)}
function f33(p){
if(p&&p.indexOf(':/')==-1&&p.indexOf(':\\')==-1&&p.indexOf('/')!=0) return unescape(absPath)+p
else return p}
function addLoadHandler(lh){
if(lh){
if(!document.loadHandlers){
document.loadHandlers=new Array()
document.loadHandlers[0]=lh
document.lastLoadHandler=0}
else{
document.lastLoadHandler++
document.loadHandlers[document.lastLoadHandler]=lh}}}
addLoadHandler('f29')
addLoadHandler(window.onload)
window.onload=f31
function f32(){return true;}
window.onerror=f32
function resetPopup(popup){
if(popup&&popup.children){
var i
for(i=0;i<popup.children.length;i++){
if(popup.children[i].id.indexOf('sep')==-1){
popup.children[i].style.color=popup.v06
popup.children[i].style.backgroundColor=popup.v08}}}}
function buildPopup(q,v12,level){
var v09
if(level>q.maxlev){v09=eval("q.lev"+q.maxlev);}else{v09=eval("q.lev"+level);}
var popupName=v12+"popup"
q.v18.document.write("<div id='"+popupName+"' style='position:absolute;top:1000;padding-left:"+q.bord+";padding-top:"+q.bord+";padding-right:"+q.bord+";padding-bottom:"+q.bord+";visibility:hidden'>")
var array=eval(v12)
var v13
var ali=" align='"+(q.v22==1?'center':(q.v22==2?'right':'left'))+"' "
for(v13=0;v13<array.length/5;v13++){
if(v13>0&&q.sep)q.v18.document.write("<div id='"+popupName+v13+'sep'+"' style='background-color:"+q.borderCol+";height:"+q.sep+";width:"+(q.v23-q.bord*2)+"'></div>")
var v30=(array[v13*5+2])?(v12+"_"+parseInt(v13+1)):null
var iconTag=(array[v13*5+2]?"<IMG SRC=\'"+f33(q.v21)+"/"+q.fnm+"ia.gif\' BORDER=0 WIDTH="+q.iconSize+" HEIGHT="+q.iconSize+" HSPACE=0 ALIGN=RIGHT>":"")
var v26=array[v13*5]
var style="width:"+(q.v23-q.bord*2-q.vertSpace*2)+";padding-left:"+q.vertSpace+";padding-top:"+q.vertSpace+";padding-bottom:"+q.vertSpace
style+=";font-size:"+v09[0]+";width:"+(q.v23-q.vertSpace*2-q.bord*2)+";color:"+v09[3]+";font-family:"+v09[6]
if(v09[1])style+=";font-weight:bold"
if(v09[2])style+=";font-style:italic"
q.v18.document.write("<div"+ali+"id='"+(popupName+v13)+"' style=\""+style+"\">"+iconTag+v26+"</div>")}
q.v18.document.write("<div style='height:0'>&nbsp;</div>")
q.v18.document.write("</div>")
for(v13=0;v13<array.length/5;v13++){
if(array[v13*5+2])buildPopup(q,v12+'_'+(v13+1),level+1)}}
function buildPopups(){
var nmn
var pf
for(nmn=1;nmn<=lastm;nmn++){
var q=eval("window.m"+nmn)
if(q&&(!q.v19||q.v20)){
q.v18=(q.v19&&!q.v20)?findFr(window.top,q.v24):window
targetFrame=(q.v19)?findFr(window.top,q.cntFrame):window
var i=1
while(true){
var menu=eval(q.name+'mn'+i)
if(!menu)break
buildPopup(q,q.name+'mn'+i,0)
i++}
pf=q.v18}}
if(pf)pf.document.close()}
buildPopups()
function f03(q,popup,id,v27,v26,v30,v09,bLast,v31,target,icon){
var itemWnd=findElement(q.v18,id)
f30(itemWnd,"mouseover",f22,false)
f30(itemWnd,"mouseout",f23,false)
f30(itemWnd,"mousedown",f20,false)
f30(itemWnd,"dblclick",f20,false)
itemWnd.owner=popup
with(itemWnd.style){
if(v27){cursor="hand";}
else{cursor="default";}
backgroundColor=v09[4]?v09[4]:'white'
f04(itemWnd,q.v23,2*q.bord)}
if(v30)itemWnd.v30=v30
itemWnd.url=f33(v27)
itemWnd.dispText=v26
itemWnd.target=target
itemWnd.icon=icon
return itemWnd.offsetHeight}
function f04(wnd,width,borderWidth){
wnd.style.pixelWidth=width-borderWidth
if(wnd.style.pixelWidth>width-borderWidth)wnd.style.pixelWidth=width-parseInt(wnd.style.paddingLeft)-parseInt(wnd.style.paddingRight)}
function f05(q,v12,level){
var popupName=v12+"popup"
var popup=findElement(q.v18,popupName)
if(popup&&popup.bCreated)return popup
if(q.v17&&q.v17.id==popupName)q.v17=null
var v09
if(level>q.maxlev){v09=eval("q.lev"+q.maxlev);}else{v09=eval("q.lev"+level);}
popup.level=level
popup.v05=v09[5]
popup.v06=v09[3]
popup.v07=v09[7]?v09[7]:'white'
popup.v08=v09[4]?v09[4]:'white'
popup.scrVis=false
popup.bCreated=true
popup.q=q
with(popup.style){
zIndex=maxZ
position="absolute"
width=q.v23
borderColor=q.borderCol
backgroundColor=q.bord?q.borderCol:(v09[4]?v09[4]:'white')
borderWidth=q.bord
borderStyle="solid"}
f30(popup,"mouseout",f15,false)
f30(popup,"mouseover",f14,false)
var v31=0
var array=eval(v12)
var v13
for(v13=0;v13<array.length/5;v13++){
var v30=(array[v13*5+2])?(v12+"_"+parseInt(v13+1)):null
v31+=f03(q,popup,(popupName+v13),array[v13*5+1],array[v13*5],v30,v09,(v13==array.length/5-1),v31,array[v13*5+3],array[v13*5+4])}
return popup}
function f35(wnd,vis){
var i=1
while(true){
var eln='HideItem'
if(i>1)eln+=i
var hideWnd=findElement(wnd,eln)
if(!hideWnd)break
hideWnd.style.visibility=vis ? 'visible' : 'hidden'
i++}}
function f06(q,popupId,dl){
if(popupId.indexOf('_')==-1){
f35(q.v18,1)
if(q.actm&&dl)chgBg(q,q.actm,0,1)}
var popup=findElement(q.v18,popupId)
if(popup){
resetPopup(popup)
if(popup.v14)f06(q,popup.v14.id)
popup.style.visibility="hidden"}
if(q.v17&&q.v17.id==popupId)q.v17=null}
function f07(rect,refx,refy){
var retval=new rct(rect.left-refx,rect.top-refy,rect.right-refx,rect.bottom-refy)
return retval}
function f34(popup,actEl){
var items=popup.getElementsByTagName("DIV")
var i=0
for(;i<items.length;i++)if(actEl!=items[i]&&(!items[i].id||items[i].id.indexOf("scroll")==-1)){
items[i].style.backgroundColor=popup.v08
items[i].style.color=popup.v06}}
function f08(q,popup,x,y,bDontMove,refWnd){
if(popup.id.indexOf('_')==-1)
f35(q.v18,0)
popup.style.pixelLeft=x
popup.style.pixelTop=y
popup.style.visibility="visible"
var v15=f19(q,popup)
var v16=f17(q.v18)
if(v15.right>v16.right){
if(refWnd&&refWnd.id&&refWnd.id.indexOf('top')==-1)popup.style.pixelLeft=Math.max(0,refWnd.offsetLeft-popup.offsetWidth+q.levelOffset)
else popup.style.pixelLeft=v16.right-popup.offsetWidth-5}
f34(popup,null)}
function f13(q,popup){
var wnd=q.v17
while(wnd){
if(wnd.id==popup.id)
return true
wnd=wnd.v14}
return false}
function f14(){
var q=this.q
if(q.v17&&f13(q,this))clearTimeout(q.v17Timeout)}
function f15(){
var q=this.q
f15Impl(q,this)}
function f15Impl(q,popup){
if(q.mout&&q.v17&&f13(q,popup)){
if(q.v17Timeout)clearTimeout(q.v17Timeout)
q.v17Timeout=setTimeout("f06("+q.name+",'"+q.v17.id+"',1);",q.closeDelay)}}
function rct(left,top,right,bottom){
this.left=left
this.top=top
this.right=right
this.bottom=bottom}
function getBody(frame){
var bodyArr=frame.document.getElementsByTagName('body')
return bodyArr[0]}
function f17(doc){
var body=getBody(doc)
var left=body.style.pixelLeft
var top=body.style.pixelTop
var right=left+body.style.pixelWidth
var bottom=top+body.style.pixelHeight
var retval=new rct(left,top,right,bottom)
return retval}
function f19(q,wnd){
var left=0
var top=0
var right=0
var bottom=0
var par=wnd
while(par){
left+=par.offsetLeft
top+=par.offsetTop
if(par.offsetParent==par || par.offsetParent==getBody(q.v18))break
par=par.offsetParent}
right=left+wnd.offsetWidth
bottom=top+wnd.offsetHeight
var retval=new rct(left,top,right,bottom)
return retval}
function findFr(wn,fr){
if(wn.frames){
for(var i=0;i<wn.frames.length;i++){
if(wn.frames[i].name==fr)return wn.frames[i]
var ret=findFr(wn.frames[i],fr)
if(ret)return ret}}
return null}
function f20(){
var item=this
var q=this.owner.q
if(item.url){
var trgFrame=q.cntFrame
if(item.target)
trgFrame=item.target
if(trgFrame=="_self")
trgFrame=null
if(trgFrame){
if(trgFrame=="_blank")window.open(item.url)
else if(trgFrame=="_top")window.top.location.href=item.url
else if(trgFrame=="_parent")parent.location.href=item.url
else{
var fr=findFr(window.top,trgFrame)
if(fr)fr.location.href=item.url
else window.location.href=item.url}}
else{
var find=item.url.indexOf("javascript:")
if(find!=-1)
eval(item.url.substring(find))
else{
var mt=item.url.indexOf("mailto:")
if(mt!=-1)window.location=item.url.substring(mt)
else if(q.v18!=window)window.open(item.url)
else targetFrame.location=item.url}}
if(q.v17)f06(q,q.v17.id,1)}}
function f22(){
var item=this
var q=this.owner.q
if(item.owner.v14){
resetPopup(item.owner)
f06(q,item.owner.v14.id)}
if(item.url&&item.url.indexOf("javascript:")==-1)
window.status=item.url
else
window.status=""
f34(item.owner,null)
item.style.color=item.owner.v05
item.style.backgroundColor=item.owner.v07
var items=item.owner.getElementsByTagName("DIV")
if(item.v30){
var rect=f19(q,item)
var x=rect.right-q.levelOffset
var y=rect.top
var popup=f05(q,item.v30,item.owner.level+1)
item.owner.v14=popup
f08(q,popup,x,y+2,false,item.owner)}}
function f23(){
var item=this
var q=this.owner.q
window.status=""}
function exM(q,popupId,refWnd,dum,ml,mt,mr,mb){
if(!docLoaded)return
clearTimeout(q.v17Timeout)
if(q.v17&&q.v17.id!=popupId+"popup")
f06(q,q.v17.id)
if(popupId=='none')return
var rect
if(refWnd=='coords'){rect=f19(q,findElement(0,q.name+'tl'));rect.left=rect.left+ml;rect.top=rect.top+mt;rect.right=rect.left+mr;rect.bottom=rect.top+mb;}else{rect=f19(q,findElement(0,refWnd));}
var x
var y
x=rect.left
y=rect.bottom+q.popupOffset
var popup=f05(q,popupId,0)
f08(q,popup,x,y,true,null)
q.v17=popup}
function coM(q,popupId){
if(!docLoaded)return
var popup=findElement(q.v18,popupId+"popup")
if(popup)f15Impl(q,popup)}
function exMNS(q,popupId,e,dItem){}
function coMNS(q,popupId){}
function f28(){
var nmn
for(nmn=1;nmn<lastm;nmn++){
var q=eval("window.m"+nmn)
if(q&&q.v17)f06(q,q.v17.id,1)}}
function f29(){
if(docLoaded)return
var nmn
for(nmn=1;nmn<lastm;nmn++){
var q=eval("window.m"+nmn)
if(q&&!q.mout)f30(q.v18.document,"mousedown",f28,false)}
docLoaded=true}
function f30(obj,event,fun,bubble){
if(obj.addEventListener)
obj.addEventListener(event,fun,bubble)
else
eval("obj.on"+event+"="+fun)}
function chgBg(q,item,color,cl){
var el=findElement(0,item)
if(color==0){
if(cl){
if(!q.v25)el.style.background=q.tlmOrigBg
el.style.color=q.tlmOrigCol}}
else{
if(q.actm)chgBg(q,q.actm,0,1)
if(!q.v25&&(color&1))el.style.background=q.tlmHlBg
if(color&2)el.style.color=q.tlmHlCol
q.actm=item}}
function f31(){
var i
var l=document.lastLoadHandler
document.lastLoadHandler=-1
for(i=0;i<=l;i++){
var h=document.loadHandlers[i]
if(typeof(h)!='function'){
var bPar=(h.indexOf('(')==-1)
eval(h+(bPar ? '();' : ';'))}
else{
h()}}}
