//script generated by SiteXpert (www.xtreeme.com)
//Copyright(C) 1998-2003 Xtreeme GmbH
function ap2(p,a){
if(p&&p.indexOf(':/')==-1&&p.indexOf(':\\')==-1&&p.indexOf('/')!=0) return unescape(a)+p
else return p}
function findFr(wn,fr){
if(wn.frames){
for(var i=0;i<wn.frames.length;i++){
if(wn.frames[i].name==fr)return wn.frames[i]
var ret=findFr(wn.frames[i],fr)
if(ret)return ret}}
return null}
function buildPopup(q,v12,level){
var v09
if(level>q.maxlev){v09=eval("q.lev"+q.maxlev);}else{v09=eval("q.lev"+level);}
var popupName=v12+"popup"
q.v18.document.write("<div id='"+popupName+"' style='position:absolute;padding-left:"+q.bord+";padding-top:"+q.bord+";padding-right:"+q.bord+";padding-bottom:"+q.bord+";visibility:hidden'>")
var frm=findFr(window.top,q.menuFrame)
var array=eval("frm."+v12)
var v13
var ali=" align='"+(q.v22==1?'center':(q.v22==2?'right':'left'))+"' "
for(v13=0;v13<array.length/5;v13++){
if(v13>0&&q.sep)q.v18.document.write("<div id='"+popupName+v13+'sep'+"' style='background-color:"+q.borderCol+";height:"+q.sep+";width:"+(q.v23-q.bord*2)+"'></div>")
var v30=(array[v13*5+2])?(v12+"_"+parseInt(v13+1)):null
var iconTag=(array[v13*5+2]?"<IMG SRC=\'"+ap2(q.v21,frm.absPath)+"/"+q.fnm+"ia.gif\' BORDER=0 WIDTH="+q.iconSize+" HEIGHT="+q.iconSize+" HSPACE=0 ALIGN=RIGHT>":"")
var v26=array[v13*5]
var style="width:"+(q.v23-q.bord*2-q.vertSpace*2)+";padding-left:"+q.vertSpace+";padding-top:"+q.vertSpace+";padding-bottom:"+q.vertSpace
style+=";font-size:"+v09[0]+";width:"+(q.v23-q.vertSpace*2-q.bord*2)+";color:"+v09[3]+";font-family:"+v09[6]
if(v09[1])style+=";font-weight:bold"
if(v09[2])style+=";font-style:italic"
q.v18.document.write("<div"+ali+"id='"+(popupName+v13)+"' style=\""+style+"\">"+iconTag+v26+"</div>")}
q.v18.document.write("<div style='height:0'>&nbsp;</div>")
q.v18.document.write("</div>")
for(v13=0;v13<array.length/5;v13++){
if(array[v13*5+2])buildPopup(q,v12+'_'+(v13+1),level+1)}}
function buildPopups(){
var nmn
var pf
var frm=findFr(window.top,q.menuFrame)
for(nmn=1;nmn<=frm.lastm;nmn++){
var q=eval("frm.m"+nmn)
if(q){
q.v18=(q.v19&&!q.v20)?findFr(window.top,q.v24):frm
targetFrame=(q.v19)?findFr(window.top,q.cntFrame):frm
var i=1
while(true){
var menu=eval("frm."+q.name+"mn"+i)
if(!menu)break
buildPopup(q,q.name+'mn'+i,0)
i++}
pf=q.v18}}
if(pf)pf.document.close()}
var Opera=(navigator.userAgent.indexOf('Opera')!=-1)||(navigator.appName.indexOf('Opera')!=-1)||(window.opera)
var Opera7=(Opera&&document.createElement!=null&&document.addEventListener!=null)
if(Opera&&!Opera7){buildPopups();}
