vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|11 May 2007 08:18:46 -0000
vti_extenderversion:SR|4.0.2.8912
vti_cacheddtm:TX|11 May 2007 08:18:46 -0000
vti_filesize:IR|71799
vti_cachedlinkinfo:VX|S|menu.js S|valorpunto.js S|funciones.js H|<? echo $Ruta_red.($Siniestro->Fields.$Item["Id"].$Value); ?> S|Imagenes/carpeta.gif H|SiniestroActualizar.asp S|Imagenes/pencil.gif H|SiniestroBorrar.asp S|Imagenes/borrar.gif H|etiqueta.asp S|Imagenes/etiqueta.jpg H|Cliente.asp H|ContratoImprimir.asp H|ContratoPrestacionDeServicios.asp H|ContratoPrestacionDeServicios.asp H|AgendaInsertar.asp S|Imagenes/bell.gif H|SiniestroActualizar.asp H|ContrarioModificar.asp H|ContrarioBorrar.asp S|Imagenes/borrar.gif H|ContrarioInsertar.asp H|Siniestro.asp H|Siniestro.asp H|ProfesionalModificar.asp H|SiniestroProfesionalModificar.asp S|Imagenes/pencil.gif H|SiniestroProfesionalBorrar.asp S|Imagenes/Borrar.gif H|AutorizacionCompromisoDePago.asp S|Imagenes/AutComp.jpg H|AutorizacionCompromisoDePago.asp S|Imagenes/AutComp.jpg H|SolicitudAbogadoProcurador.asp S|Imagenes/AutComp.jpg H|FacturaInsertar.asp S|Imagenes/facturas.jpg H|SiniestroProfesionalInsertar.asp S|Imagenes/alerta.gif H|FacturaModificar.asp S|Imagenes/pencil.gif H|FacturasBorrar.asp S|Imagenes/Borrar.gif H|FacturaModificar.asp S|Imagenes/pencil.gif H|FacturasBorrar.asp S|Imagenes/Borrar.gif H|FacturaInsertar.asp H|LibroSuplidos.asp H|LibroSuplidos.asp S|Imagenes/excel.gif H|LibroSuplidos2.asp H|LibroSuplidos2.asp S|Imagenes/excel.gif A|SiniestroIndemnizacionActualizar.asp S|Imagenes/calculadora2.gif S|ValorPunto.js H|IndemnizacionFinal.asp H|IndemnizacionFinal.asp S|Imagenes/excel.gif A|SiniestroNotasActualizar.asp H|<? echo $cadena; ?>/<? echo $x->Name; ?> H|CorrespondenciaModificar.asp S|Imagenes/pencil.gif H|CorrespondenciaBorrar.asp S|Imagenes/Borrar.gif H|CorrespondenciaInsertar.asp H|DocClienteModificar.asp S|Imagenes/pencil.gif H|DocClienteBorrar.asp S|Imagenes/Borrar.gif H|DocClienteInsertar.asp
vti_cachedsvcrellinks:VX|FSUS|avata/menu.js FSUS|avata/valorpunto.js FSUS|avata/funciones.js UHUS|<? echo $Ruta_red.($Siniestro->Fields.$Item["Id"].$Value); ?> FSUS|avata/Imagenes/carpeta.gif FHUS|avata/SiniestroActualizar.asp FSUS|avata/Imagenes/pencil.gif FHUS|avata/SiniestroBorrar.asp FSUS|avata/Imagenes/borrar.gif FHUS|avata/etiqueta.asp FSUS|avata/Imagenes/etiqueta.jpg FHUS|avata/Cliente.asp FHUS|avata/ContratoImprimir.asp FHUS|avata/ContratoPrestacionDeServicios.asp FHUS|avata/ContratoPrestacionDeServicios.asp FHUS|avata/AgendaInsertar.asp FSUS|avata/Imagenes/bell.gif FHUS|avata/SiniestroActualizar.asp FHUS|avata/ContrarioModificar.asp FHUS|avata/ContrarioBorrar.asp FSUS|avata/Imagenes/borrar.gif FHUS|avata/ContrarioInsertar.asp FHUS|avata/Siniestro.asp FHUS|avata/Siniestro.asp FHUS|avata/ProfesionalModificar.asp FHUS|avata/SiniestroProfesionalModificar.asp FSUS|avata/Imagenes/pencil.gif FHUS|avata/SiniestroProfesionalBorrar.asp FSUS|avata/Imagenes/Borrar.gif FHUS|avata/AutorizacionCompromisoDePago.asp FSUS|avata/Imagenes/AutComp.jpg FHUS|avata/AutorizacionCompromisoDePago.asp FSUS|avata/Imagenes/AutComp.jpg FHUS|avata/SolicitudAbogadoProcurador.asp FSUS|avata/Imagenes/AutComp.jpg FHUS|avata/FacturaInsertar.asp FSUS|avata/Imagenes/facturas.jpg FHUS|avata/SiniestroProfesionalInsertar.asp FSUS|avata/Imagenes/alerta.gif FHUS|avata/FacturaModificar.asp FSUS|avata/Imagenes/pencil.gif FHUS|avata/FacturasBorrar.asp FSUS|avata/Imagenes/Borrar.gif FHUS|avata/FacturaModificar.asp FSUS|avata/Imagenes/pencil.gif FHUS|avata/FacturasBorrar.asp FSUS|avata/Imagenes/Borrar.gif FHUS|avata/FacturaInsertar.asp FHUS|avata/LibroSuplidos.asp FHUS|avata/LibroSuplidos.asp FSUS|avata/Imagenes/excel.gif FHUS|avata/LibroSuplidos2.asp FHUS|avata/LibroSuplidos2.asp FSUS|avata/Imagenes/excel.gif FAUS|avata/SiniestroIndemnizacionActualizar.asp FSUS|avata/Imagenes/calculadora2.gif FSUS|avata/ValorPunto.js FHUS|avata/IndemnizacionFinal.asp FHUS|avata/IndemnizacionFinal.asp FSUS|avata/Imagenes/excel.gif FAUS|avata/SiniestroNotasActualizar.asp UHUS|<? echo $cadena; ?>/<? echo $x->Name; ?> FHUS|avata/CorrespondenciaModificar.asp FSUS|avata/Imagenes/pencil.gif FHUS|avata/CorrespondenciaBorrar.asp FSUS|avata/Imagenes/Borrar.gif FHUS|avata/CorrespondenciaInsertar.asp FHUS|avata/DocClienteModificar.asp FSUS|avata/Imagenes/pencil.gif FHUS|avata/DocClienteBorrar.asp FSUS|avata/Imagenes/Borrar.gif FHUS|avata/DocClienteInsertar.asp
vti_cachedtitle:SR|Datos del siniestro
vti_title:SR|Datos del siniestro
vti_cachedbodystyle:SR|<body bgcolor="#FFFFFF" text="#000000" topmargin="30" <? if (($Siniestro->Fields$Item["Fase"]$Value==70))
{
  print "background=\"Imagenes/ExpCerrado.gif\"";} 
}
  else
{
print " background=\"Imagenes/fondo.gif\" bgproperties=\"fixed\"";?>>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=iso-8859-1 HTTP-EQUIV=pragma no-cache
vti_backlinkinfo:VX|avata/cliente.asp avata/principal.asp avata/agentemodificar.asp avata/facturaslistadosalida.asp avata/listadocobradossalida.asp avata/listadoconabogadoysinaj.asp avata/siniestro.asp avata/comisionessincobrar.asp avata/facturasadelantadas.asp avata/siniestroslistar2salida.asp avata/clienteresultadobusqueda2.asp avata/listadoproblemasaj.asp avata/pagossinhacer.asp avata/siniestroresultadobusqueda.asp avata/siniestroslistarsalida.asp

